name: add a label to an issue

on:
  issues:
    type:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "test-issue"
        
