name: job-summary

on: 
  workflow_dispatch:

jobs:
  job-summary:
    runs-on: ubuntu-latest
    steps:
      - id: st-1
        run: echo 'hello'
      - run: |
          if ${{ steps.st-1.conclusion == success }}; then
            echo 'st-1 successfully completed' >> $GITHUB_STEP_SUMMARY
          else
            echo 'st-1 is failed' >> $GITHUB_STEP_SUMMARY
